---

- name: Add Server Packages (yum)
  hosts: interop1:interop2
  become: True
  become_method: sudo
  tags: server
  roles:
    - server_pkgs

- name: Per-user Tasks
  hosts: interop1:interop2
  become: True
  become_method: sudo
  vars_files:
#    - main_interop1.yml
#    - students_interop.yml
#     - students_p1.yml
#     - students_p2.yml
#     - students_p3.yml
#     - students_p4.yml
     - students_p5.yml
#     - students_p6.yml
  tags: interop
  roles:
    - python_pkgs
    - ansible_general
    - netmiko
    - arista
    - juniper 
    - nexus
    - { role: napalm, tags: napalm }
    - ansible_extras
